spring.application.name=instructor
management.endpoints.web.exposure.include=beans

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/instructor_db
spring.datasource.username=postgres
spring.datasource.password=maria17
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
