--liquibase formatted sql

--changeset JosMaria:001
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255),
    role VARCHAR(20),
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts ADD CONSTRAINT uc_accounts_username UNIQUE (username);
